Language : python3

python :
      -  '3.10'

install : 
      - pip install -e .
      - pip install pytest-cov codecov

script : 
      - pytest tests
      - pytest --cov= transformations tests 
      
after_success :
      - codecov